bibentry(bibtype = "Book",
         key = "Atkinson:1989",
         author = person(given = c("Kendall", "E."),
                         family = "Atkinson"),
         title = "An Introduction to Numerical Analysis",
         publisher = "John Wiley & Sons",
         year = "1989",
         isbn = "0471624896",
         edition = "Second")

bibentry(bibtype = "Article",
         key = "Banerjee+Dhillon+Ghosh:2005",
         author = c(person(given = "Arindam",
                           family = "Banerjee"),
                    person(given = c("Inderjit", "S."),
                           family = "Dhillon"),
                    person(given = "Joydeep",
                           family = "Ghosh"),
                    person(given = "Suvrit",
                           family = "Sra")),
         title = "Clustering on the Unit Hypersphere using {von Mises--Fisher} Distributions",
         journal = "Journal of Machine Learning Research",
         year = "2005",
         volume = "6",
         number = "46",
         pages = "1345--1382",
         url = "https://jmlr.org/papers/v6/banerjee05a.html")

bibentry(bibtype = "Article",
         key = "Celeux+Govaert:1992",
         title = "A classification EM algorithm for clustering and two stochastic versions",
         volume = "14",
         .issn = "0167-9473",
         doi = "10.1016/0167-9473(92)90042-e",
         number = "3",
         journal = "Computational Statistics & Data Analysis",
         publisher = "Elsevier BV",
         author = c(person(given = "Gilles",
                           family = "Celeux"),
                    person(given = "Gérard",
                           family = "Govaert")),
         year = "1992",
         month = "oct",
         pages = "315--332")

bibentry(bibtype = "Article",
         key = "Hornik+Grün:2013",
         title = "Amos-type bounds for modified {Bessel} function ratios",
         volume = "408",
         .issn = "0022-247X",
         doi = "10.1016/j.jmaa.2013.05.070",
         number = "1",
         journal = "Journal of Mathematical Analysis and Applications",
         publisher = "Elsevier BV",
         author = c(person(given = "Kurt",
                           family = "Hornik",
                           comment = c(ORCID = "0000-0003-4198-9911")),
                    person(given = "Bettina",
                           family = "Grün",
                           comment = c(ORCID = "0000-0001-7265-4773"))),
         year = "2013",
         month = "dec",
         pages = "91--101")

bibentry(bibtype = "Article",
         key = "Hornik+Grün:2014",
         title = "On Maximum Likelihood Estimation of the Concentration Parameter of {von Mises--Fisher} Distributions",
         volume = "29",
         .issn = "1613-9658",
         doi = "10.1007/s00180-013-0471-0",
         number = "5",
         journal = "Computational Statistics",
         publisher = "Springer Science and Business Media LLC",
         author = c(person(given = "Kurt",
                           family = "Hornik",
                           comment = c(ORCID = "0000-0003-4198-9911")),
                    person(given = "Bettina",
                           family = "Grün",
                           comment = c(ORCID = "0000-0001-7265-4773"))),
         year = "2014",
         month = "oct",
         pages = "945--957")

bibentry(bibtype = "Book",
         key = "Press+Teukolsky+Vetterling:1992",
         author = c(person(given = c("William", "H."),
                           family = "Press"),
                    person(given = c("Saul", "A."),
                           family = "Teukolsky"),
                    person(given = c("William", "T."),
                           family = "Vetterling"),
                    person(given = c("Brian", "P."),
                           family = "Flannery")),
         title = "Numerical Recipes in {C}: The Art of Scientific Computing",
         publisher = "Cambridge University Press",
         year = "1992",
         edition = "Second",
         isbn = "978-0521431088")

bibentry(bibtype = "Article",
         key = "Song+Liu+Wang:2012",
         title = "High-order Parameter Approximation for {von Mises--Fisher} Distributions",
         volume = "218",
         .issn = "0096-3003",
         doi = "10.1016/j.amc.2012.05.050",
         number = "24",
         journal = "Applied Mathematics and Computation",
         publisher = "Elsevier BV",
         author = c(person(given = "Heping",
                           family = "Song"),
                    person(given = "Jun",
                           family = "Liu"),
                    person(given = "Guoli",
                           family = "Wang")),
         year = "2012",
         month = "aug",
         pages = "11880--11890")

bibentry(bibtype = "Article",
         key = "Sra:2012",
         title = "A Short Note on Parameter Approximation for {von Mises--Fisher} Distributions: and a Fast Implementation of $I_s(x)$",
         volume = "27",
         .issn = "1613-9658",
         doi = "10.1007/s00180-011-0232-x",
         number = "1",
         journal = "Computational Statistics",
         publisher = "Springer Science and Business Media LLC",
         author = person(given = "Suvrit",
                         family = "Sra"),
         year = "2012",
         pages = "177--190")

bibentry(bibtype = "Article",
         key = "Tanabe+Fukumizu+Oba:2007",
         title = "Parameter Estimation for {von Mises--Fisher} Distributions",
         volume = "22",
         .issn = "1613-9658",
         doi = "10.1007/s00180-007-0030-7",
         number = "1",
         journal = "Computational Statistics",
         publisher = "Springer Science and Business Media LLC",
         author = c(person(given = "Akihiro",
                           family = "Tanabe"),
                    person(given = "Kenji",
                           family = "Fukumizu"),
                    person(given = "Shigeyuki",
                           family = "Oba"),
                    person(given = "Takashi",
                           family = "Takenouchi"),
                    person(given = "Shin",
                           family = "Ishii")),
         year = "2007",
         month = "mar",
         pages = "145--157")

bibentry(bibtype = "Article",
         key = "Wood:1994",
         author = person(given = c("Andrew", "T.", "A."),
                         family = "Wood"),
         title = "Simulation of the {von Mises Fisher} Distribution",
         journal = "Communications in Statistics -- Simulation and Computation",
         year = "1994",
         volume = "23",
         number = "1",
         pages = "157--164",
         doi = "10.1080/03610919408813161")
